export const DAILY_ISLAND = [
  {
    name: "에라스모의 섬",
    src: "/img/island/island_10.png",
    time: ["06:00", "14:00", "20:00"],
    lv: 355,
    position: "대항해",
    contType: "ISLAND",
  },
  {
    name: "환각의 섬",
    src: "/img/island/island_00.png",
    time: [
      "00:00",
      "02:00",
      "04:00",
      "06:00",
      "08:00",
      "10:00",
      "12:00",
      "14:00",
      "16:00",
      "18:00",
      "20:00",
      "22:00",
    ],
    lv: 250,
    position: "대항해",
    contType: "ISLAND",
  },
  {
    name: "무릉도원",
    src: "/img/island/island_04.png",
    time: ["00:00", "06:00", "12:00", "18:00"],
    lv: 400,
    position: "대항해",
    contType: "ISLAND",
  },
  {
    name: "잠자는 노래의 섬",
    src: "/img/island/island_05.png",
    time: [
      "00:20",
      "03:20",
      "06:20",
      "09:20",
      "12:20",
      "15:20",
      "18:20",
      "21:20",
    ],
    lv: 250,
    position: "대항해",
    contType: "ISLAND",
  },
  {
    name: "두키 섬",
    src: "/img/island/island_06.png",
    time: ["00:50", "04:50", "08:50", "12:50", "16:50", "20:50"],
    lv: 250,
    position: "대항해",
    contType: "ISLAND",
  },
  {
    name: "그릇된 욕망의 섬",
    src: "/img/island/island_07.png",
    time: ["01:20", "07:20", "13:20", "19:20"],
    lv: 250,
    position: "대항해",
    contType: "ISLAND",
  },
  {
    name: "스피다 섬",
    src: "/img/island/island_08.png",
    time: ["01:40", "07:40", "13:40", "19:40", "22:40"],
    lv: 250,
    position: "대항해",
    contType: "ISLAND",
  },
  {
    name: "알라케르",
    src: "/img/island/island_09.png",
    time: ["01:50", "07:50", "13:50", "19:50"],
    lv: 302,
    position: "대항해",
    contType: "ISLAND",
  },

  {
    name: "신월의 섬",
    src: "/img/island/island_02.png",
    time: ["03:00", "07:00", "11:00", "15:00", "19:00", "23:00"],
    lv: 250,
    position: "대항해",
    contType: "ISLAND",
  },
  {
    name: "미지의 섬",
    src: "/img/island/island_01.png",
    time: ["00:20", "04:20", "10:20", "13:20", "16:20", "22:20"],
    lv: 460,
    position: "대항해",
    contType: "ISLAND",
  },
];

// 캘린더섬 리스트
export const CALENDAR_ISLAND: {
  [key: string]: {
    name: string;
    src: string;
    lv: number;
    position: string;
    contType: string;
  };
} = {
  "기회의 섬": {
    name: "기회의 섬",
    src: "/img/calendar/calendar_00.jpg",
    lv: 505,
    position: "대항해",
    contType: "ISLAND",
  },
  수라도: {
    name: "수라도",
    src: "/img/calendar/calendar_01.jpg",
    lv: 400,
    position: "대항해",
    contType: "ISLAND",
  },
  포르페: {
    name: "포르페",
    src: "/img/calendar/calendar_02.jpg",
    lv: 325,
    position: "대항해",
    contType: "ISLAND",
  },
  "쿵덕쿵 아일랜드": {
    name: "쿵덕쿵 아일랜드",
    src: "/img/calendar/calendar_03.jpg",
    lv: 250,
    position: "대항해",
    contType: "ISLAND",
  },
  "볼라르 섬": {
    name: "볼라르 섬",
    src: "/img/calendar/calendar_04.jpg",
    lv: 250,
    position: "대항해",
    contType: "ISLAND",
  },
  "블루홀 섬": {
    name: "블루홀 섬",
    src: "/img/calendar/calendar_05.jpg",
    lv: 1005,
    position: "대항해",
    contType: "ISLAND",
  },
  "하모니 섬": {
    name: "하모니 섬",
    src: "/img/calendar/calendar_06.jpg",
    lv: 400,
    position: "대항해",
    contType: "ISLAND",
  },
  "고요한 안식의 섬": {
    name: "고요한 안식의 섬",
    src: "/img/calendar/calendar_07.jpg",
    lv: 505,
    position: "대항해",
    contType: "ISLAND",
  },
  "몬테 섬": {
    name: "몬테 섬",
    src: "/img/calendar/calendar_08.jpg",
    lv: 900,
    position: "대항해",
    contType: "ISLAND",
  },
  "죽음의 협곡": {
    name: "죽음의 협곡",
    src: "/img/calendar/calendar_09.jpg",
    lv: 400,
    position: "대항해",
    contType: "ISLAND",
  },
  메데이아: {
    name: "메데이아",
    src: "/img/calendar/calendar_10.jpg",
    lv: 250,
    position: "대항해",
    contType: "ISLAND",
  },
  "스노우팡 아일랜드": {
    name: "스노우팡 아일랜드",
    src: "/img/calendar/calendar_11.jpg",
    lv: 250,
    position: "대항해",
    contType: "ISLAND",
  },
  "환영 나비의 섬": {
    name: "환영 나비의 섬",
    src: "/img/calendar/calendar_12.jpg",
    lv: 460,
    position: "대항해",
    contType: "ISLAND",
  },
  "우거진 갈대의 섬": {
    name: "우거진 갈대섬",
    src: "/img/calendar/calendar_13.jpg",
    lv: 505,
    position: "대항해",
    contType: "ISLAND",
  },
};

const partTime1 = [
  "11:00",
  "12:00",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
  "18:00",
  "19:00",
  "20:00",
  "21:00",
  "22:00",
  "23:00",
];
const partTime2 = ["00:00", "01:00", "02:00", "03:00", "04:00", "05:00"];
const partTime3 = [...partTime2, ...partTime1];
const partTime1End = "05:00";
const partTime2End = "05:00";

// 필드보스 일월화수목금토
export const FIELD_BOSS = [
  [
    {
      id: 1,
      name: "시그나투스",
      lv: 310,
      position: "아르데타인-갈라진 땅",
      src: "/img/boss/boss_06.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 2,
      name: "타르실라",
      lv: 340,
      position: "슈샤이어-머무른 시간의 호수",
      src: "/img/boss/boss_02.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },

    {
      id: 4,
      name: "솔 그랑데",
      lv: 370,
      position: "대항해-알트아이젠",
      src: "/img/boss/boss_01.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 5,
      name: "혼재의 추오",
      lv: 385,
      position: "애니츠-소리의 숲",
      src: "/img/boss/boss_09.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 6,
      name: "프록시마",
      lv: 415,
      position: "베른 북부-베르닐 산림",
      src: "/img/boss/boss_00.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 8,
      name: "브리아레오스",
      lv: 505,
      position: "대항해-얼음과 불의 섬",
      src: "/img/boss/boss_03.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 9,
      name: "하르마게돈",
      lv: 550,
      position: "로헨델-파괴된 제나일",
      src: "/img/boss/boss_08.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 10,
      name: "강림하신 호박신",
      lv: 885,
      position: "대항해-오르비스",
      src: "/img/boss/boss_05.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 11,
      name: "티파니",
      lv: 915,
      position: "욘-무쇠망치 작업장",
      src: "/img/boss/boss_10.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 12,
      name: "아우리온",
      lv: 960,
      position: "대항해-격류의 섬",
      src: "/img/boss/boss_07.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 13,
      name: "엔켈라두스",
      lv: 1050,
      position: "페이튼-붉은 달의 흔적",
      src: "/img/boss/boss_11.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 14,
      name: "모아케",
      lv: 1415,
      position: "파푸니카-티키타카 군락지",
      src: "/img/boss/boss_13.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 15,
      name: "천둥날개",
      lv: 1460,
      position: "베른 남부-칸다리아 영지",
      src: "/img/boss/boss_14.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
  ],
  [
    {
      id: 1,
      name: "시그나투스",
      lv: 310,
      position: "아르데타인-갈라진 땅",
      src: "/img/boss/boss_06.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 2,
      name: "타르실라",
      lv: 340,
      position: "슈샤이어-머무른 시간의 호수",
      src: "/img/boss/boss_02.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },

    {
      id: 4,
      name: "솔 그랑데",
      lv: 370,
      position: "대항해-알트아이젠",
      src: "/img/boss/boss_01.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 5,
      name: "혼재의 추오",
      lv: 385,
      position: "애니츠-소리의 숲",
      src: "/img/boss/boss_09.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 6,
      name: "프록시마",
      lv: 415,
      position: "베른 북부-베르닐 산림",
      src: "/img/boss/boss_00.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },

    {
      id: 8,
      name: "브리아레오스",
      lv: 505,
      position: "대항해-얼음과 불의 섬",
      src: "/img/boss/boss_03.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 9,
      name: "하르마게돈",
      lv: 550,
      position: "로헨델-파괴된 제나일",
      src: "/img/boss/boss_08.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 10,
      name: "강림하신 호박신",
      lv: 885,
      position: "대항해-오르비스",
      src: "/img/boss/boss_05.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 11,
      name: "티파니",
      lv: 915,
      position: "욘-무쇠망치 작업장",
      src: "/img/boss/boss_10.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 12,
      name: "아우리온",
      lv: 960,
      position: "대항해-격류의 섬",
      src: "/img/boss/boss_07.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 13,
      name: "엔켈라두스",
      lv: 1050,
      position: "페이튼-붉은 달의 흔적",
      src: "/img/boss/boss_11.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 14,
      name: "모아케",
      lv: 1415,
      position: "파푸니카-티키타카 군락지",
      src: "/img/boss/boss_13.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 15,
      name: "천둥날개",
      lv: 1460,
      position: "베른 남부-칸다리아 영지",
      src: "/img/boss/boss_14.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
  ],
  [
    {
      id: 1,
      name: "시그나투스",
      lv: 310,
      position: "아르데타인-갈라진 땅",
      src: "/img/boss/boss_06.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 2,
      name: "타르실라",
      lv: 340,
      position: "슈샤이어-머무른 시간의 호수",
      src: "/img/boss/boss_02.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },

    {
      id: 4,
      name: "솔 그랑데",
      lv: 370,
      position: "대항해-알트아이젠",
      src: "/img/boss/boss_01.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 5,
      name: "혼재의 추오",
      lv: 385,
      position: "애니츠-소리의 숲",
      src: "/img/boss/boss_09.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 6,
      name: "프록시마",
      lv: 415,
      position: "베른 북부-베르닐 산림",
      src: "/img/boss/boss_00.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },

    {
      id: 8,
      name: "브리아레오스",
      lv: 505,
      position: "대항해-얼음과 불의 섬",
      src: "/img/boss/boss_03.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 9,
      name: "하르마게돈",
      lv: 550,
      position: "로헨델-파괴된 제나일",
      src: "/img/boss/boss_08.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 10,
      name: "강림하신 호박신",
      lv: 885,
      position: "대항해-오르비스",
      src: "/img/boss/boss_05.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 11,
      name: "티파니",
      lv: 915,
      position: "욘-무쇠망치 작업장",
      src: "/img/boss/boss_10.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 12,
      name: "아우리온",
      lv: 960,
      position: "대항해-격류의 섬",
      src: "/img/boss/boss_07.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 13,
      name: "엔켈라두스",
      lv: 1050,
      position: "페이튼-붉은 달의 흔적",
      src: "/img/boss/boss_11.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 14,
      name: "모아케",
      lv: 1415,
      position: "파푸니카-티키타카 군락지",
      src: "/img/boss/boss_13.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 15,
      name: "천둥날개",
      lv: 1460,
      position: "베른 남부-칸다리아 영지",
      src: "/img/boss/boss_14.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
  ],
  [
    {
      id: 1,
      name: "시그나투스",
      lv: 310,
      position: "아르데타인-갈라진 땅",
      src: "/img/boss/boss_06.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 2,
      name: "타르실라",
      lv: 340,
      position: "슈샤이어-머무른 시간의 호수",
      src: "/img/boss/boss_02.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },

    {
      id: 4,
      name: "솔 그랑데",
      lv: 370,
      position: "대항해-알트아이젠",
      src: "/img/boss/boss_01.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 5,
      name: "혼재의 추오",
      lv: 385,
      position: "애니츠-소리의 숲",
      src: "/img/boss/boss_09.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 6,
      name: "프록시마",
      lv: 415,
      position: "베른 북부-베르닐 산림",
      src: "/img/boss/boss_00.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },

    {
      id: 8,
      name: "브리아레오스",
      lv: 505,
      position: "대항해-얼음과 불의 섬",
      src: "/img/boss/boss_03.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 9,
      name: "하르마게돈",
      lv: 550,
      position: "로헨델-파괴된 제나일",
      src: "/img/boss/boss_08.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 10,
      name: "강림하신 호박신",
      lv: 885,
      position: "대항해-오르비스",
      src: "/img/boss/boss_05.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 11,
      name: "티파니",
      lv: 915,
      position: "욘-무쇠망치 작업장",
      src: "/img/boss/boss_10.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 12,
      name: "아우리온",
      lv: 960,
      position: "대항해-격류의 섬",
      src: "/img/boss/boss_07.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 13,
      name: "엔켈라두스",
      lv: 1050,
      position: "페이튼-붉은 달의 흔적",
      src: "/img/boss/boss_11.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 14,
      name: "모아케",
      lv: 1415,
      position: "파푸니카-티키타카 군락지",
      src: "/img/boss/boss_13.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 15,
      name: "천둥날개",
      lv: 1460,
      position: "베른 남부-칸다리아 영지",
      src: "/img/boss/boss_14.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
  ],
  [],
  [
    {
      id: 1,
      name: "시그나투스",
      lv: 310,
      position: "아르데타인-갈라진 땅",
      src: "/img/boss/boss_06.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 2,
      name: "타르실라",
      lv: 340,
      position: "슈샤이어-머무른 시간의 호수",
      src: "/img/boss/boss_02.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },

    {
      id: 4,
      name: "솔 그랑데",
      lv: 370,
      position: "대항해-알트아이젠",
      src: "/img/boss/boss_01.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 5,
      name: "혼재의 추오",
      lv: 385,
      position: "애니츠-소리의 숲",
      src: "/img/boss/boss_09.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 6,
      name: "프록시마",
      lv: 415,
      position: "베른 북부-베르닐 산림",
      src: "/img/boss/boss_00.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },

    {
      id: 8,
      name: "브리아레오스",
      lv: 505,
      position: "대항해-얼음과 불의 섬",
      src: "/img/boss/boss_03.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 9,
      name: "하르마게돈",
      lv: 550,
      position: "로헨델-파괴된 제나일",
      src: "/img/boss/boss_08.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 10,
      name: "강림하신 호박신",
      lv: 885,
      position: "대항해-오르비스",
      src: "/img/boss/boss_05.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 11,
      name: "티파니",
      lv: 915,
      position: "욘-무쇠망치 작업장",
      src: "/img/boss/boss_10.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 12,
      name: "아우리온",
      lv: 960,
      position: "대항해-격류의 섬",
      src: "/img/boss/boss_07.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 13,
      name: "엔켈라두스",
      lv: 1050,
      position: "페이튼-붉은 달의 흔적",
      src: "/img/boss/boss_11.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 14,
      name: "모아케",
      lv: 1415,
      position: "파푸니카-티키타카 군락지",
      src: "/img/boss/boss_13.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
    {
      id: 15,
      name: "천둥날개",
      lv: 1460,
      position: "베른 남부-칸다리아 영지",
      src: "/img/boss/boss_14.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      contType: "FIELD_BOSS",
    },
  ],
  [
    {
      id: 1,
      name: "시그나투스",
      lv: 310,
      position: "아르데타인-갈라진 땅",
      src: "/img/boss/boss_06.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 2,
      name: "타르실라",
      lv: 340,
      position: "슈샤이어-머무른 시간의 호수",
      src: "/img/boss/boss_02.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },

    {
      id: 4,
      name: "솔 그랑데",
      lv: 370,
      position: "대항해-알트아이젠",
      src: "/img/boss/boss_01.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 5,
      name: "혼재의 추오",
      lv: 385,
      position: "애니츠-소리의 숲",
      src: "/img/boss/boss_09.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 6,
      name: "프록시마",
      lv: 415,
      position: "베른 북부-베르닐 산림",
      src: "/img/boss/boss_00.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },

    {
      id: 8,
      name: "브리아레오스",
      lv: 505,
      position: "대항해-얼음과 불의 섬",
      src: "/img/boss/boss_03.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 9,
      name: "하르마게돈",
      lv: 550,
      position: "로헨델-파괴된 제나일",
      src: "/img/boss/boss_08.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 10,
      name: "강림하신 호박신",
      lv: 885,
      position: "대항해-오르비스",
      src: "/img/boss/boss_05.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 11,
      name: "티파니",
      lv: 915,
      position: "욘-무쇠망치 작업장",
      src: "/img/boss/boss_10.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 12,
      name: "아우리온",
      lv: 960,
      position: "대항해-격류의 섬",
      src: "/img/boss/boss_07.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 13,
      name: "엔켈라두스",
      lv: 1050,
      position: "페이튼-붉은 달의 흔적",
      src: "/img/boss/boss_11.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 14,
      name: "모아케",
      lv: 1415,
      position: "파푸니카-티키타카 군락지",
      src: "/img/boss/boss_13.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
    {
      id: 15,
      name: "천둥날개",
      lv: 1460,
      position: "베른 남부-칸다리아 영지",
      src: "/img/boss/boss_14.png",
      time: partTime2,
      endTime: partTime2End,
      contType: "FIELD_BOSS",
    },
  ],
];

// 카오스게이트
export const CHAOS_GATE = [
  [
    {
      name: "일렁이는 질병군단",
      src: "/img/chaos/chaos_01.png",
      time: partTime3,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 802,
      position: "욘-미완의 정원",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 어둠군단",
      src: "/img/chaos/chaos_04.png",
      time: partTime3,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 960,
      position: "페이튼-울부짖는 늪지대",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 광기군단",
      src: "/img/chaos/chaos_02.png",
      time: partTime3,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 1302,
      position: "파푸니카-별모래 해변",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 ??군단",
      src: "/img/chaos/chaos_05.png",
      time: partTime3,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 1415,
      position: "베른 남부-칸다리아 영지",
      contType: "CHAOS_GATE",
    },
  ],
  [
    {
      name: "일렁이는 질병군단",
      src: "/img/chaos/chaos_01.png",
      time: partTime3,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 802,
      position: "욘-미완의 정원",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 어둠군단",
      src: "/img/chaos/chaos_04.png",
      time: partTime3,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 960,
      position: "페이튼-울부짖는 늪지대",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 광기군단",
      src: "/img/chaos/chaos_02.png",
      time: partTime3,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 1302,
      position: "파푸니카-별모래 해변",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 ??군단",
      src: "/img/chaos/chaos_05.png",
      time: partTime3,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 1415,
      position: "베른 남부-칸다리아 영지",
      contType: "CHAOS_GATE",
    },
  ],
  [
    {
      name: "일렁이는 질병군단",
      src: "/img/chaos/chaos_01.png",
      time: partTime2,
      endTime: partTime2End,
      lv: 802,
      position: "욘-미완의 정원",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 어둠군단",
      src: "/img/chaos/chaos_04.png",
      time: partTime2,
      endTime: partTime2End,
      lv: 960,
      position: "페이튼-울부짖는 늪지대",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 광기군단",
      src: "/img/chaos/chaos_02.png",
      time: partTime2,
      endTime: partTime2End,
      lv: 1302,
      position: "파푸니카-별모래 해변",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 ??군단",
      src: "/img/chaos/chaos_05.png",
      time: partTime2,
      endTime: partTime2End,
      lv: 1415,
      position: "베른 남부-칸다리아 영지",
      contType: "CHAOS_GATE",
    },
  ],
  [],
  [
    {
      name: "일렁이는 질병군단",
      src: "/img/chaos/chaos_01.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 802,
      position: "욘-미완의 정원",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 어둠군단",
      src: "/img/chaos/chaos_04.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 960,
      position: "페이튼-울부짖는 늪지대",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 광기군단",
      src: "/img/chaos/chaos_02.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 1302,
      position: "파푸니카-별모래 해변",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 ??군단",
      src: "/img/chaos/chaos_05.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 1415,
      position: "베른 남부-칸다리아 영지",
      contType: "CHAOS_GATE",
    },
  ],
  [
    {
      name: "일렁이는 질병군단",
      src: "/img/chaos/chaos_01.png",
      time: partTime2,
      endTime: partTime2End,
      lv: 802,
      position: "욘-미완의 정원",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 어둠군단",
      src: "/img/chaos/chaos_04.png",
      time: partTime2,
      endTime: partTime2End,
      lv: 960,
      position: "페이튼-울부짖는 늪지대",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 광기군단",
      src: "/img/chaos/chaos_02.png",
      time: partTime2,
      endTime: partTime2End,
      lv: 1302,
      position: "파푸니카-별모래 해변",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 ??군단",
      src: "/img/chaos/chaos_05.png",
      time: partTime2,
      endTime: partTime2End,
      lv: 1415,
      position: "베른 남부-칸다리아 영지",
      contType: "CHAOS_GATE",
    },
  ],
  [
    {
      name: "일렁이는 질병군단",
      src: "/img/chaos/chaos_01.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 802,
      position: "욘-미완의 정원",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 어둠군단",
      src: "/img/chaos/chaos_04.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 960,
      position: "페이튼-울부짖는 늪지대",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 광기군단",
      src: "/img/chaos/chaos_02.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 1302,
      position: "파푸니카-별모래 해변",
      contType: "CHAOS_GATE",
    },
    {
      name: "일렁이는 ??군단",
      src: "/img/chaos/chaos_05.png",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
      lv: 1415,
      position: "베른 남부-칸다리아 영지",
      contType: "CHAOS_GATE",
    },
  ],
];

// 항해
export const OCEAN_ACT = [
  [
    {
      name: "기에나",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["아르데타인", "베른", "애니츠"],
      endPosition: "애니츠",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
    {
      name: "프로키온",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["페이튼", "파푸니카", "로헨델"],
      endPosition: "로헨델",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
  ],
  [
    {
      name: "기에나",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["아르데타인", "애니츠", "베른"],
      endPosition: "베른",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
    {
      name: "프로키온",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["페이튼", "로헨델", "욘"],
      endPosition: "욘",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
    {
      name: "조화의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-베른 북부", "대항해-베른 북부"],
      endPosition: "대항해-베른 북부",
      time: ["18:00", "22:00"],
      endTime: "22:00",
      waiting: 1,
    },
    {
      name: "대지의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-욘"],
      endPosition: "대항해-욘",
      time: ["18:00"],
      endTime: "18:00",
      waiting: 1,
    },
    {
      name: "인내의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-페이튼"],
      endPosition: "대항해-페이튼",
      time: ["18:00"],
      endTime: "18:00",
      waiting: 1,
    },
    {
      name: "지혜의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-로헨델"],
      endPosition: "대항해-로헨델",
      time: ["22:00"],
      endTime: "22:00",
      waiting: 1,
    },
    {
      name: "인도의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-파푸니카"],
      endPosition: "대항해-파푸니카",
      time: ["22:00"],
      endTime: "22:00",
      waiting: 1,
    },
  ],
  [
    {
      name: "기에나",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["애니츠", "베른", "아르데타인"],
      endPosition: "아르데타인",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
    {
      name: "프로키온",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["파푸니카", "욘", "로헨델"],
      endPosition: "로헨델",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
  ],
  [
    {
      name: "기에나",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["베른", "아르데타인", "애니츠"],
      endPosition: "애니츠",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
    {
      name: "프로키온",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["욘", "페이튼", "파푸니카"],
      endPosition: "파푸니카",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
    {
      name: "조화의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-베른 북부", "대항해-베른 북부"],
      endPosition: "대항해-베른 북부",
      time: ["18:00", "22:00"],
      endTime: "22:00",
      waiting: 1,
    },
    {
      name: "지혜의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: "대항해-로헨델",
      endPosition: "대항해-로헨델",
      time: ["18:00"],
      endTime: "18:00",
      waiting: 1,
    },
    {
      name: "인도의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-파푸니카"],
      endPosition: "대항해-파푸니카",
      time: ["18:00"],
      endTime: "18:00",
      waiting: 1,
    },
    {
      name: "대지의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-욘"],
      endPosition: "대항해-욘",
      time: ["22:00"],
      endTime: "22:00",
      waiting: 1,
    },
    {
      name: "인내의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-페이튼"],
      endPosition: "대항해-페이튼",
      time: ["22:00"],
      endTime: "22:00",
      waiting: 1,
    },
  ],
  [
    {
      name: "기에나",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["아르데타인", "애니츠", "베른"],
      endPosition: "베른",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
    {
      name: "프로키온",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["로헨델", "파푸니카", "페이튼"],
      endPosition: "페이튼",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
  ],
  [
    {
      name: "기에나",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["애니츠", "페이튼", "베른"],
      endPosition: "베른",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
    {
      name: "프로키온",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["페이튼", "로헨델", "욘"],
      endPosition: "욘",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
  ],
  [
    {
      name: "기에나",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["베른", "아르데타인", "애니츠"],
      endPosition: "애니츠",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
    {
      name: "프로키온",
      contType: "CO_OCEAN",
      lv: "-",
      src: "/img/ocean/ocean_01.png",
      position: ["로헨델", "욘", "파푸니카"],
      endPosition: "파푸니카",
      time: ["19:30", "21:30", "23:30"],
      endTime: "23:30",
    },
    {
      name: "조화의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-베른 북부", "대항해-베른 북부"],
      endPosition: "대항해-베른 북부",
      time: ["18:00", "23:00"],
      endTime: "23:00",
      waiting: 1,
    },
    {
      name: "대지의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-욘"],
      endPosition: "대항해-욘",
      time: ["18:00"],
      endTime: "18:00",
      waiting: 1,
    },
    {
      name: "인내의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-페이튼"],
      endPosition: "대항해-페이튼",
      time: ["18:00"],
      endTime: "18:00",
      waiting: 1,
    },
    {
      name: "지혜의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-로헨델"],
      endPosition: "대항해-로헨델",
      time: ["23:00"],
      endTime: "23:00",
      waiting: 1,
    },
    {
      name: "인도의 관문",
      contType: "GATE",
      lv: "-",
      src: "/img/ocean/ocean_02.png",
      position: ["대항해-파푸니카"],
      endPosition: "대항해-파푸니카",
      time: ["23:00"],
      endTime: "23:00",
      waiting: 1,
    },
  ],
];

// 유령선
export const PHANTOM_SHIP = [
  [
    {
      name: "악몽을 떠도는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 460,
      src: "/img/ocean/ocean_03.png",
      position: "로헨델",
      endPosition: "로헨델",
      time: partTime2,
      endTime: partTime2End,
    },
    {
      name: "그림자를 헤매는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 960,
      src: "/img/ocean/ocean_03.png",
      position: "페이튼",
      endPosition: "페이튼",
      time: partTime2,
      endTime: partTime2End,
    },
    {
      name: "폭풍을 부르는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 1370,
      src: "/img/ocean/ocean_03.png",
      position: "파푸니카",
      endPosition: "파푸니카",
      time: partTime2,
      endTime: partTime2End,
    },
  ],
  [],
  [
    {
      name: "악몽을 떠도는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 460,
      src: "/img/ocean/ocean_03.png",
      position: "로헨델",
      endPosition: "로헨델",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
    },
    {
      name: "그림자를 헤매는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 960,
      src: "/img/ocean/ocean_03.png",
      position: "페이튼",
      endPosition: "페이튼",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
    },
    {
      name: "폭풍을 부르는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 1370,
      src: "/img/ocean/ocean_03.png",
      position: "파푸니카",
      endPosition: "파푸니카",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
    },
  ],
  [
    {
      name: "악몽을 떠도는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 460,
      src: "/img/ocean/ocean_03.png",
      position: "로헨델",
      endPosition: "로헨델",
      time: partTime2,
      endTime: partTime2End,
    },
    {
      name: "그림자를 헤매는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 960,
      src: "/img/ocean/ocean_03.png",
      position: "페이튼",
      endPosition: "페이튼",
      time: partTime2,
      endTime: partTime2End,
    },
    {
      name: "폭풍을 부르는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 1370,
      src: "/img/ocean/ocean_03.png",
      position: "파푸니카",
      endPosition: "파푸니카",
      time: partTime2,
      endTime: partTime2End,
    },
  ],
  [
    {
      name: "악몽을 떠도는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 460,
      src: "/img/ocean/ocean_03.png",
      position: "로헨델",
      endPosition: "로헨델",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
    },
    {
      name: "그림자를 헤매는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 960,
      src: "/img/ocean/ocean_03.png",
      position: "페이튼",
      endPosition: "페이튼",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
    },
    {
      name: "폭풍을 부르는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 1370,
      src: "/img/ocean/ocean_03.png",
      position: "파푸니카",
      endPosition: "파푸니카",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
    },
  ],
  [
    {
      name: "악몽을 떠도는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 460,
      src: "/img/ocean/ocean_03.png",
      position: "로헨델",
      endPosition: "로헨델",
      time: partTime2,
      endTime: partTime2End,
    },
    {
      name: "그림자를 헤매는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 960,
      src: "/img/ocean/ocean_03.png",
      position: "페이튼",
      endPosition: "페이튼",
      time: partTime2,
      endTime: partTime2End,
    },
    {
      name: "폭풍을 부르는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 1370,
      src: "/img/ocean/ocean_03.png",
      position: "파푸니카",
      endPosition: "파푸니카",
      time: partTime2,
      endTime: partTime2End,
    },
  ],
  [
    {
      name: "악몽을 떠도는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 460,
      src: "/img/ocean/ocean_03.png",
      position: "로헨델",
      endPosition: "로헨델",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
    },
    {
      name: "그림자를 헤매는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 960,
      src: "/img/ocean/ocean_03.png",
      position: "페이튼",
      endPosition: "페이튼",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
    },
    {
      name: "폭풍을 부르는 유령선",
      contType: "PHANTOM_SHIP",
      lv: 1370,
      src: "/img/ocean/ocean_03.png",
      position: "파푸니카",
      endPosition: "파푸니카",
      time: partTime1,
      additionalTime: partTime2,
      endTime: partTime1End,
    },
  ],
];
